<?php

declare(strict_types=1);

namespace Statnive\Service;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Resolve a visitor's IANA timezone to an ISO 3166-1 alpha-2 country code.
 *
 * Pure in-process lookup against a static table generated from public-domain
 * IANA tzdb sources. No network, no external service — first-party browser
 * data already present in the tracker payload. Used as the final tier of the
 * GeoIP fallback chain when neither MaxMind nor a CDN country header is
 * available.
 *
 * The lookup table is generated by bin/build-timezone-countries.php and lives
 * at src/Data/timezone-countries.php. See that file's docblock for the design
 * choices around multi-country zones and `backward` aliases.
 */
final class TimezoneGeoResolver {

	/**
	 * Lazy-loaded tz → ISO country code map.
	 *
	 * @var array<string, string>|null
	 */
	private static ?array $map = null;

	/**
	 * Generic offset zones we never attempt to resolve. Anything matching this
	 * pattern carries no country signal.
	 */
	private const UNRESOLVABLE_PATTERN = '#^(Etc/|UTC$|GMT|[-+]\d)#';

	/**
	 * Resolve a timezone string to an ISO 3166-1 alpha-2 country code.
	 *
	 * Returns an empty string when the timezone is empty, an offset zone, or
	 * absent from the lookup table. Never guesses.
	 *
	 * @param string $tz IANA timezone identifier (e.g. "America/New_York").
	 */
	public static function resolve( string $tz ): string {
		if ( '' === $tz ) {
			return '';
		}
		if ( preg_match( self::UNRESOLVABLE_PATTERN, $tz ) ) {
			return '';
		}

		if ( null === self::$map ) {
			/**
			 * IANA timezone → ISO 3166-1 alpha-2 lookup map.
			 *
			 * @var array<string, string> $map
			 */
			$map       = require __DIR__ . '/../Data/timezone-countries.php';
			self::$map = $map;
		}

		return self::$map[ $tz ] ?? '';
	}

	/**
	 * Reset the cached map. Test helper only.
	 */
	public static function clear_cache(): void {
		self::$map = null;
	}
}
