<?php

declare(strict_types=1);

namespace Statnive\Admin;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * React SPA asset handler for WordPress admin.
 *
 * Enqueues the compiled React dashboard and injects configuration
 * via wp_localize_script. Only loads on the Statnive admin page.
 */
final class ReactHandler {

	/**
	 * Hook suffix for the Statnive top-level admin page.
	 *
	 * Generated by WordPress from the menu slug `'statnive'` registered in
	 * {@see AdminMenuManager}. Used as the single source of truth for the
	 * page-scoping guard so dashboard CSS/JS never leak into other admin
	 * screens. See `CLAUDE.md` → "Admin Asset Scoping Rule".
	 */
	public const HOOK_SUFFIX = 'toplevel_page_statnive';

	/**
	 * Hook into WordPress admin.
	 */
	public static function init(): void {
		add_action( 'admin_enqueue_scripts', [ self::class, 'enqueue_assets' ] );
	}

	/**
	 * Enqueue React SPA assets on the Statnive admin page only.
	 *
	 * @param string $hook_suffix The current admin page hook.
	 */
	public static function enqueue_assets( string $hook_suffix ): void {
		if ( self::HOOK_SUFFIX !== $hook_suffix ) {
			return;
		}

		$manifest = self::read_manifest();
		if ( empty( $manifest ) ) {
			return;
		}

		// Find the main entry point from Vite manifest.
		$main_entry = $manifest['resources/react/main.tsx'] ?? null;
		if ( null === $main_entry ) {
			return;
		}

		$base_url = plugins_url( 'public/react/', STATNIVE_FILE );

		// Enqueue the main JS bundle.
		$js_url = $base_url . ( $main_entry['file'] ?? '' );
		wp_enqueue_script(
			'statnive-dashboard',
			$js_url,
			[ 'wp-element', 'wp-i18n' ],
			STATNIVE_VERSION,
			true
		);

		// Wire up @wordpress/i18n translation loading for the React dashboard.
		// JSON files generated via `wp i18n make-json languages/ --no-purge`
		// after .po files are translated.
		wp_set_script_translations(
			'statnive-dashboard',
			'statnive',
			plugin_dir_path( STATNIVE_FILE ) . 'languages'
		);

		// Enqueue CSS if present.
		if ( ! empty( $main_entry['css'] ) ) {
			foreach ( $main_entry['css'] as $index => $css_file ) {
				wp_enqueue_style(
					'statnive-dashboard-' . $index,
					$base_url . $css_file,
					[],
					STATNIVE_VERSION
				);
			}
		}

		// Inject dashboard configuration.
		wp_localize_script(
			'statnive-dashboard',
			'StatniveDashboard',
			[
				'restUrl'   => rest_url( 'statnive/v1/' ),
				'nonce'     => wp_create_nonce( 'wp_rest' ),
				'siteTitle' => get_bloginfo( 'name' ),
				'version'   => STATNIVE_VERSION,
			]
		);

		// Build import map for dynamic chunks so lazy imports resolve correctly.
		$import_map = self::build_import_map( $manifest, $base_url );

		// Add module type + import map to script tag.
		add_filter(
			'script_loader_tag',
			static function ( string $tag, string $handle ) use ( $import_map ): string {
				if ( 'statnive-dashboard' !== $handle ) {
					return $tag;
				}

				// Inject import map before the module script.
				// wp_get_inline_script_tag() wraps content in CDATA on non-html5 themes,
				// which breaks importmap JSON parsing. Output directly instead.
				$importmap_tag = '';
				if ( ! empty( $import_map ) ) {
					$importmap_json = wp_json_encode( [ 'imports' => $import_map ], JSON_UNESCAPED_SLASHES );
					// phpcs:ignore WordPress.WP.EnqueuedResources.NonEnqueuedScript -- importmap is data, not executable JS; content from wp_json_encode is safe.
					$importmap_tag = '<script type="importmap">' . $importmap_json . '</script>' . "\n";
				}

				$tag = str_replace( ' src=', ' type="module" src=', $tag );
				return $importmap_tag . $tag;
			},
			10,
			2
		);
	}

	/**
	 * Build an import map from the Vite manifest.
	 *
	 * Maps relative chunk paths (e.g., "./chunk-abc.js") to full plugin URLs
	 * so dynamic imports resolve correctly in WordPress admin context.
	 *
	 * @param array<string, mixed> $manifest  Parsed Vite manifest.
	 * @param string               $base_url  Plugin assets base URL.
	 * @return array<string, string> Import map entries.
	 */
	private static function build_import_map( array $manifest, string $base_url ): array {
		$map = [];

		foreach ( $manifest as $entry ) {
			$file = $entry['file'] ?? '';
			if ( empty( $file ) ) {
				continue;
			}

			// Map both relative (./) and bare chunk references to full URLs.
			$filename                = basename( $file );
			$full_url                = $base_url . $file;
			$map[ './' . $filename ] = $full_url;
		}

		return $map;
	}

	/**
	 * Read the Vite manifest file.
	 *
	 * @return array<string, mixed> Parsed manifest, or empty array on failure.
	 */
	private static function read_manifest(): array {
		$manifest_path = STATNIVE_PATH . 'public/react/.vite/manifest.json';
		if ( ! file_exists( $manifest_path ) ) {
			return [];
		}

		// Local plugin file path, not a remote URL — wp_remote_get() does
		// not apply. file_get_contents() is the correct primitive here.
		// phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
		$content = file_get_contents( $manifest_path );
		if ( false === $content ) {
			return [];
		}

		$decoded = json_decode( $content, true );
		return is_array( $decoded ) ? $decoded : [];
	}
}
